# Generated by Django 3.2 on 2021-04-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Funcionario', '0001_initial'),
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_baia', models.CharField(max_length=300)),
                ('capacidade', models.PositiveIntegerField()),
                ('definicao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaiasMTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Animal.animal')),
                ('Funcionaios', models.ManyToManyField(to='Funcionario.Funcionario')),
                ('nome_baias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Baias.baias')),
            ],
        ),
    ]
