# Generated by Django 3.2 on 2021-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0001_initial'),
        ('Baias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baias',
            name='Funcionarios',
            field=models.ManyToManyField(to='Funcionario.Funcionario'),
        ),
        migrations.DeleteModel(
            name='BaiasMTM',
        ),
    ]
