# Generated by Django 3.2 on 2021-04-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baias',
            name='id_funcionario_responsavel',
        ),
        migrations.RemoveField(
            model_name='baias',
            name='nome_funcionario',
        ),
    ]
