# Generated by Django 3.2 on 2021-04-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0002_remove_funcionario_id_funcionario'),
        ('Baias', '0002_auto_20210417_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='baias',
            name='Funcionarios',
            field=models.ManyToManyField(to='Funcionario.Funcionario'),
        ),
    ]
