# Generated by Django 3.2 on 2021-04-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0003_alter_animal_obs'),
        ('Baias', '0003_baias_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='baias',
            name='Animais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Animal.animal'),
        ),
    ]
