# Generated by Django 3.2 on 2021-04-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0004_baias_animais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baias',
            name='Funcionarios',
        ),
    ]
