# Generated by Django 3.2 on 2021-04-18 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0004_remove_animal_id_baia_pertence'),
        ('Funcionario', '0006_remove_funcionario_baia'),
        ('Baias', '0005_remove_baias_funcionarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baias',
            name='Animais',
        ),
        migrations.CreateModel(
            name='BaiasMTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Animal.animal')),
                ('Funcionaios', models.ManyToManyField(to='Funcionario.Funcionario')),
                ('nome_baia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Baias.baias')),
            ],
        ),
    ]
