# Generated by Django 3.2 on 2021-04-18 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0006_auto_20210417_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baiasmtm',
            old_name='nome_baia',
            new_name='nome_baias',
        ),
    ]
