# Generated by Django 3.2 on 2021-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=300)),
                ('idade_animal', models.PositiveIntegerField()),
                ('tipo_animal', models.CharField(max_length=300)),
                ('peso_animal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
