# Generated by Django 3.2 on 2021-04-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='obs',
            field=models.TextField(null=True),
        ),
    ]
