# Generated by Django 3.2 on 2021-04-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0001_initial'),
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='baia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Baias.baias'),
            preserve_default=False,
        ),
    ]
