# Generated by Django 3.2 on 2021-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0002_alter_animal_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
