# Generated by Django 3.2 on 2021-04-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0003_alter_animal_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id_baia_pertence',
        ),
    ]
