# Generated by Django 3.2 on 2021-04-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0002_auto_20210420_2313'),
        ('Animal', '0004_alter_animal_baia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='baia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Baias.baias'),
        ),
    ]
