# Generated by Django 3.2 on 2021-04-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('funcao', models.CharField(max_length=300)),
                ('id_funcionario', models.PositiveIntegerField()),
            ],
        ),
    ]
