# Generated by Django 3.2 on 2021-04-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id_funcionario',
        ),
    ]
