# Generated by Django 3.2 on 2021-04-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0005_remove_baias_funcionarios'),
        ('Funcionario', '0002_remove_funcionario_id_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='Baia',
            field=models.ManyToManyField(to='Baias.Baias'),
        ),
    ]
