# Generated by Django 3.2 on 2021-04-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0005_remove_baias_funcionarios'),
        ('Funcionario', '0003_funcionario_baia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='Baia',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Baia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Baias.baias'),
        ),
    ]
