# Generated by Django 3.2 on 2021-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baias', '0005_remove_baias_funcionarios'),
        ('Funcionario', '0004_auto_20210417_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='Baia',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='Baia',
            field=models.ManyToManyField(to='Baias.Baias'),
        ),
    ]
