# Generated by Django 3.2 on 2021-04-18 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionario', '0005_auto_20210417_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='Baia',
        ),
    ]
